In [ ]:
a. Using NumPy create random vector of size 15 having only Integers in the range 1-20.
1. Reshape the array to 3 by 5
2. Print array shape.
3. Replace the max in each row by 0

In [1]:
import numpy as np

arr = np.random.randint(1, 21, size=15)

arr = arr.reshape(3, 5)

print("Shape of array:", arr.shape)

print("Original array:\n", arr)

for i in range(arr.shape[0]):
    maxx = arr[i].argmax()
    arr[i][maxx] = 0

print("Modified array:\n", arr)


Shape of array: (3, 5)
Original array:
 [[ 3  2  3 19  7]
 [ 8 19 16  3 19]
 [13  4  8 14 18]]
Modified array:
 [[ 3  2  3  0  7]
 [ 8  0 16  3 19]
 [13  4  8 14  0]]


In [ ]:
b. Create a 2-dimensional array of size 4 x 3 (composed of 4-byte integer elements), also print the shape, type and data
type of the array.

In [2]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9],
                [10, 11, 12]])

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Type:", type(arr))
print("Data type:", arr.dtype)


Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data type: int32


In [ ]:
c. Write a program to compute the eigenvalues and right eigenvectors of a given square array given below:
[[ 3 -2]
[ 1 0]]

In [3]:
import numpy as np

arr1 = np.array([[3, -2],
              [1,  0]])

eigenvalues, eigenvectors = np.linalg.eig(arr1)

print("Eigenvalues:")
print(eigenvalues)
print("\nRight eigenvectors:")
print(eigenvectors)


Eigenvalues:
[2. 1.]

Right eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [ ]:
d. Compute the sum of the diagonal element of a given array.
[[0 1 2]
[3 4 5]]

In [4]:
import numpy as np

arr = np.array([[0, 1, 2],
                [3, 4, 5]])

sum = np.trace(arr)

print("Sum of diagonal elements:", sum)

Sum of diagonal elements: 4


In [ ]:
e. Write a NumPy program to create a new shape to an array without changing its data.
Reshape 3x2:
[[1 2]
[3 4]
[5 6]]
Reshape 2x3:
[[1 2 3]
[4 5 6]]

In [5]:
arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])

reshaped_arr = arr.reshape(2, 3)

print("Original array:")
print(arr)

print("\nReshaped array:")
print(reshaped_arr)

Original array:
[[1 2]
 [3 4]
 [5 6]]

Reshaped array:
[[1 2 3]
 [4 5 6]]


In [ ]:
https://drive.google.com/file/d/14cKjDUXqpxwsak0j5yElVf8jiU7KB5IW/view?usp=sharing